# -*- coding: utf-8 -*-
"""number_predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BSXPZjxtSLLvg7uFILv3ItdMVXjOspZK
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
from google.colab.patches import cv2_imshow
from PIL import Image


file = '/content/drive/My Drive/number_images/2.PNG'
img = Image.open(file)
img = img.convert('L')
img = img.resize((28, 28)) 
img = np.asarray(img)
cv2_imshow(img)
img = img.astype('float32')/255
img = np.reshape(img, [28, 28, 1])
img.shape

from keras.models import load_model

model = load_model("/content/drive/My Drive/model.h5")
img = np.array([img])
model.predict_classes(img)